import { GetServerSideProps, InferGetServerSidePropsType } from "next";
import Head from "next/head";
import Image from "next/image";

import { useAtom } from "jotai";
import { useAtomValue, useHydrateAtoms } from "jotai/utils";

import { countAtom, doubleAtom } from "store";

import styles from "../styles/Home.module.css";

type ssProps = {
    initialCount: number;
};

export const getServerSideProps: GetServerSideProps<ssProps> = async () => {
    return { props: { initialCount: 42 } };
};

const Home = (props: InferGetServerSidePropsType<typeof getServerSideProps>) => {
    const initialCount = props.initialCount;

    useHydrateAtoms([[countAtom, initialCount]] as const);
    const [count, setCount] = useAtom(countAtom);
    const doubleCount = useAtomValue(doubleAtom);

    const add1 = () => {
        setCount((count) => count + 1);
    };

    const subtract1 = () => {
        setCount((count) => count - 1);
    };

    const incrementByAmount = (amount: number) => {
        setCount((count) => count + amount);
    };

    return (
        <div className={styles.container}>
            <Head>
                <title>with-jotai</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1 className={styles.title}>Counter With Jotai example</h1>
            <main className={styles.main}>
                <div>Initial count from the server: {count}</div>
                <div>Double count: {doubleCount}</div>
                <div className={"d-flex"}>
                    <button className={"btn btn-success me-2"} onClick={add1}>
                        Add 1
                    </button>
                    <button className={"btn btn-danger me-2"} onClick={subtract1}>
                        Subtract 1
                    </button>
                    <button className={"btn btn-outline-success me-2"} onClick={() => incrementByAmount(5)}>
                        Add 5
                    </button>
                    <button className={"btn btn-outline-danger"} onClick={incrementByAmount.bind(null, -5)}>
                        Subtract 5
                    </button>
                </div>
            </main>
            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    );
};

export default Home;
